import React, { useState } from 'react';
import { 
  BookOpen, 
  Search, 
  HelpCircle, 
  FileText, 
  CheckCircle2, 
  IndianRupee, 
  ShieldCheck, 
  Tag, 
  Sparkles,
  ArrowRight,
  Calculator
} from 'lucide-react';
import DisclaimerBanner from '../components/DisclaimerBanner';

const GLOSSARY_TERMS = [
  {
    term: 'PAN (Permanent Account Number)',
    category: 'Identification',
    definition: 'A unique 10-digit alphanumeric identifier issued by the Indian Income Tax Department to track financial transactions and tax liabilities.',
    example: 'Format: ABCDE1234F. Essential for opening current bank accounts, taking loans, and filing ITR.',
  },
  {
    term: 'GST (Goods and Services Tax)',
    category: 'Indirect Tax',
    definition: 'A comprehensive destination-based indirect tax levied on the supply of goods and services throughout India, replacing multiple older cascading taxes like VAT, Service Tax, and Excise.',
    example: 'When a shop sells groceries or electronics, GST is charged at standard slabs (0%, 5%, 12%, 18%, 28%) based on HSN/SAC codes.',
  },
  {
    term: 'GSTIN (GST Identification Number)',
    category: 'Identification',
    definition: 'A 15-digit state-wise unique registration number given to every business registered under the Goods and Services Tax framework.',
    example: 'Format: 08ABCDE1234F1Z5 (where the first two digits represent the state code, e.g., 08 for Rajasthan).',
  },
  {
    term: 'ITR (Income Tax Return)',
    category: 'Filing Compliance',
    definition: 'A formal declaration submitted annually by a taxpayer to the Income Tax Department stating their gross income, eligible deductions, and tax paid for a financial year.',
    example: 'Small sole proprietorship retailers commonly file ITR-3 or presumptive ITR-4 (Sugam).',
  },
  {
    term: 'TDS (Tax Deducted at Source)',
    category: 'Direct Tax',
    definition: 'Tax collected in advance at the very point of origin when a specific payment (such as salary, professional fee, contract, or rent) is made.',
    example: 'If an enterprise earns ₹50,000 for freelance graphic work, the client may deduct 10% (₹5,000) TDS and deposit it to the government linked to your PAN.',
  },
  {
    term: 'Taxable Income',
    category: 'Calculation',
    definition: 'The net base amount on which income tax is officially calculated after subtracting allowable operating business expenses and statutory chapter VI-A deductions from gross turnover.',
    example: 'Gross Sales (₹10,00,000) - Allowable Expenses (₹6,00,000) = Net Income (₹4,00,000). Taxable Income = ₹4,00,000.',
  },
  {
    term: 'Turnover',
    category: 'Financial Metric',
    definition: 'The total value of all sales, services, and receipts generated by a business during a specific financial period, without deducting any expenses.',
    example: 'A stationery store that rings up ₹15 Lakhs in counter sales across 12 months has an annual turnover of ₹15 Lakhs.',
  },
  {
    term: 'Deduction',
    category: 'Tax Savings',
    definition: 'An allowable reduction that decreases gross income, effectively lowering the final taxable income and tax liability.',
    example: 'Expenses paid for commercial electricity, shop rent, and helper salaries are deductible business expenditures under Section 37.',
  },
  {
    term: 'Invoice',
    category: 'Documentation',
    definition: 'A commercial document issued by a seller to a buyer detailing the products, quantities, agreed prices, and taxes charged for goods or services rendered.',
    example: 'A GST Tax Invoice contains supplier GSTIN, customer details, invoice serial number, date, HSN code, and tax breakdown.',
  },
  {
    term: 'Financial Year (FY)',
    category: 'Calendar',
    definition: 'The 12-month period running from April 1 of a calendar year to March 31 of the subsequent calendar year during which an individual or business earns income.',
    example: 'FY 2024-25 covers all business earnings between 1st April 2024 and 31st March 2025.',
  },
  {
    term: 'Assessment Year (AY)',
    category: 'Calendar',
    definition: 'The year immediately succeeding the Financial Year, in which the income earned during the Financial Year is formally evaluated, calculated, and filed.',
    example: 'For income earned in FY 2024-25, the corresponding Assessment Year is AY 2025-26.',
  },
  {
    term: 'Input Tax Credit (ITC)',
    category: 'Indirect Tax',
    definition: 'A mechanism under GST allowing a registered business to reduce the GST already paid on purchases from the GST liability payable on outgoing sales.',
    example: 'If you paid ₹2,000 GST on raw supplies and collect ₹3,000 GST on product sales, you only remit ₹1,000 net GST to the government using ₹2,000 ITC.',
  },
];

export default function Learn() {
  const [searchTerm, setSearchTerm] = useState('');
  const [activeCategory, setActiveCategory] = useState('All');

  const categories = ['All', ...new Set(GLOSSARY_TERMS.map((t) => t.category))];

  const filteredTerms = GLOSSARY_TERMS.filter((item) => {
    const matchesCategory = activeCategory === 'All' || item.category === activeCategory;
    const matchesSearch =
      item.term.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.definition.toLowerCase().includes(searchTerm.toLowerCase()) ||
      item.example.toLowerCase().includes(searchTerm.toLowerCase());
    return matchesCategory && matchesSearch;
  });

  return (
    <div className="space-y-12 pb-16 max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pt-6">
      {/* Disclaimer */}
      <DisclaimerBanner />

      {/* Header */}
      <div className="text-center max-w-3xl mx-auto space-y-3">
        <span className="text-xs uppercase tracking-widest text-emerald-700 font-bold">
          Educational Tax Guide
        </span>
        <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight">
          Learn Tax Fundamentals for Small Businesses
        </h1>
        <p className="text-sm sm:text-base text-slate-600">
          Demystifying compliance, income tax concepts, and bookkeeping essentials in plain, beginner-friendly language.
        </p>
      </div>

      {/* Educational Guide Cards Section */}
      <div className="space-y-6">
        <h2 className="text-xl font-bold text-slate-900 border-b border-slate-200 pb-3">
          Essential Tax Concepts
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Concept 1: What is Income Tax? */}
          <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs space-y-3">
            <div className="flex items-center gap-2.5 text-emerald-700 font-bold text-base">
              <div className="p-2 bg-emerald-50 rounded-xl">
                <IndianRupee className="w-5 h-5 text-emerald-600" />
              </div>
              <h3>What is Income Tax?</h3>
            </div>
            <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
              Income tax is a direct contribution levied by the Central Government on the net profits earned by individuals, proprietors, and companies during a financial year. The collected taxes fund public services, national defense, infrastructure, and healthcare.
            </p>
            <div className="p-3 bg-slate-50 rounded-xl text-xs text-slate-700 border border-slate-100">
              <strong>Key Takeaway:</strong> Unlike sales tax or GST, income tax is only paid on what you keep as <em>net profit</em>, not on your gross customer collections.
            </div>
          </div>

          {/* Concept 2: What is GST? */}
          <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs space-y-3">
            <div className="flex items-center gap-2.5 text-blue-700 font-bold text-base">
              <div className="p-2 bg-blue-50 rounded-xl">
                <Tag className="w-5 h-5 text-blue-600" />
              </div>
              <h3>What is GST (Goods & Services Tax)?</h3>
            </div>
            <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
              GST is a nationwide unified indirect tax collected at each point of sale. For businesses supplying goods within a single state, GST registration is typically mandatory only when annual turnover exceeds ₹40 Lakhs (or ₹20 Lakhs for services and special states).
            </p>
            <div className="p-3 bg-slate-50 rounded-xl text-xs text-slate-700 border border-slate-100">
              <strong>Key Takeaway:</strong> Micro shopkeepers below the turnover threshold do not need mandatory GST registration unless doing interstate sales or e-commerce.
            </div>
          </div>

          {/* Concept 3: What is a Tax Return? */}
          <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs space-y-3">
            <div className="flex items-center gap-2.5 text-purple-700 font-bold text-base">
              <div className="p-2 bg-purple-50 rounded-xl">
                <FileText className="w-5 h-5 text-purple-600" />
              </div>
              <h3>What is an Income Tax Return (ITR)?</h3>
            </div>
            <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
              An ITR is an official yearly statement submitted electronically on the government portal. It specifies all the income earned, expenses incurred, taxes paid (like TDS), and any refund due back to your bank account.
            </p>
            <div className="p-3 bg-slate-50 rounded-xl text-xs text-slate-700 border border-slate-100">
              <strong>Why File:</strong> Even if your income is below the taxable slab, filing an ITR creates official financial proof required for bank business loans, credit cards, and visa applications.
            </div>
          </div>

          {/* Concept 4: What is Taxable Income? */}
          <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs space-y-3">
            <div className="flex items-center gap-2.5 text-amber-700 font-bold text-base">
              <div className="p-2 bg-amber-50 rounded-xl">
                <Calculator className="w-5 h-5 text-amber-600" />
              </div>
              <h3>What is Taxable Income?</h3>
            </div>
            <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
              Taxable income is the actual base figure that tax rates apply to. The core formula for any small enterprise is:
            </p>
            <div className="p-3 bg-emerald-50 rounded-xl text-xs font-mono text-emerald-900 border border-emerald-200">
              Gross Business Income - Allowable Business Expenses = Net Profit - Eligible Deductions = <strong>Taxable Income</strong>
            </div>
            <p className="text-xs text-slate-500">
              Actual tax treatment depends on statutory regime rules and whether you elect presumptive taxation under Section 44AD.
            </p>
          </div>

          {/* Concept 5: Why Keep Invoices? */}
          <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs space-y-3">
            <div className="flex items-center gap-2.5 text-indigo-700 font-bold text-base">
              <div className="p-2 bg-indigo-50 rounded-xl">
                <CheckCircle2 className="w-5 h-5 text-indigo-600" />
              </div>
              <h3>Why Keep Invoices & Bills?</h3>
            </div>
            <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
              Invoices are legal evidence of financial transactions. Without valid purchase invoices from your suppliers, tax authorities may disallow your expense claims, leading to an artificially high reported profit and higher tax liability.
            </p>
            <div className="p-3 bg-slate-50 rounded-xl text-xs text-slate-700 border border-slate-100">
              <strong>Best Practice:</strong> File supplier purchase bills sequentially and maintain numbered sales memos for daily customer sales.
            </div>
          </div>

          {/* Concept 6: Why Track Expenses? */}
          <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs space-y-3">
            <div className="flex items-center gap-2.5 text-rose-700 font-bold text-base">
              <div className="p-2 bg-rose-50 rounded-xl">
                <BookOpen className="w-5 h-5 text-rose-600" />
              </div>
              <h3>Why Track Daily Expenses?</h3>
            </div>
            <p className="text-xs sm:text-sm text-slate-600 leading-relaxed">
              Many small retailers pay minor shop expenses in cash (transport, tea, helper wages, packaging tape) without noting them down. Over a whole year, these unrecorded expenses can add up to thousands of rupees of lost legal deductions.
            </p>
            <div className="p-3 bg-slate-50 rounded-xl text-xs text-slate-700 border border-slate-100">
              <strong>Action Tip:</strong> Use the EasyTax Income & Expense Tracker daily to ensure every genuine business expense is accounted for.
            </div>
          </div>
        </div>
      </div>

      {/* Tax Terminology / Searchable Glossary Section */}
      <div id="glossary" className="space-y-6 pt-4">
        <div className="border-b border-slate-200 pb-3 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h2 className="text-xl font-bold text-slate-900">Tax Terminology Glossary</h2>
            <p className="text-xs text-slate-500">
              Plain-English definitions with realistic examples for common Indian business tax terms
            </p>
          </div>

          {/* Search Box */}
          <div className="relative w-full sm:w-72">
            <Search className="w-4 h-4 text-slate-400 absolute left-3 top-3" />
            <input
              type="text"
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              placeholder="Search tax terms..."
              className="w-full pl-9 pr-3 py-2 text-xs border border-slate-300 rounded-xl focus:ring-2 focus:ring-emerald-500 outline-hidden bg-white shadow-2xs"
            />
          </div>
        </div>

        {/* Category Pills */}
        <div className="flex flex-wrap items-center gap-2">
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => setActiveCategory(cat)}
              className={`px-3 py-1 rounded-lg text-xs font-semibold transition cursor-pointer ${
                activeCategory === cat
                  ? 'bg-emerald-600 text-white shadow-xs'
                  : 'bg-white text-slate-600 hover:bg-slate-100 border border-slate-200'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>

        {/* Glossary Terms Cards */}
        {filteredTerms.length === 0 ? (
          <div className="text-center py-12 bg-white rounded-2xl border border-slate-200">
            <p className="text-sm text-slate-500">No tax terms found matching "{searchTerm}".</p>
            <button
              onClick={() => {
                setSearchTerm('');
                setActiveCategory('All');
              }}
              className="mt-2 text-xs text-emerald-600 font-semibold hover:underline cursor-pointer"
            >
              Clear search filter
            </button>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {filteredTerms.map((item, idx) => (
              <div
                key={idx}
                className="bg-white p-5 rounded-2xl border border-slate-200 hover:border-emerald-300 hover:shadow-xs transition flex flex-col justify-between space-y-3"
              >
                <div>
                  <div className="flex items-start justify-between gap-2 mb-1.5">
                    <h3 className="font-bold text-slate-900 text-sm">{item.term}</h3>
                    <span className="text-[10px] font-semibold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-md shrink-0">
                      {item.category}
                    </span>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed">{item.definition}</p>
                </div>

                <div className="p-2.5 bg-slate-50 rounded-xl border border-slate-100 text-[11px] text-slate-700">
                  <span className="font-semibold text-slate-900">Example: </span>
                  {item.example}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
